package com.mamboflix.model.contentdetails

data class MoreLikeThisModelClass(
    val `data`: MoreLikeThisClassData,
    val message: String,
    val status: Int
)

data class MoreLikeThisClassData(
    val episode: List<EpisodeData>,
    val more_like_this: List<MoreLikeThisData>
)

data class MoreLikeThisData(
    val actor: String,
    val banner_status: Int,
    val cat_id: String,
    val content_duration: String,
    val content_mode: Int,
    val content_type: Int,
    val created_at: String,
    val description_e: String,
    val description_s: String,
    val director: String,
    val download: Int,
    val id: Int,
    val image_e: String,
    val image: String,
    val image_s: String,
    val is_draft: String,
    val keyword: String,
    val mambo_org: String,
    val path: String,
    val poster_e: String,
    val poster_s: String,
    val related_content_id: Any,
    val is_subscribed: Int,
    val release_date: String,
    val release_year: Int,
    val runtime: Int,
    val schedule: String,
    val schedule_date_time: String,
    val slug: String,
    val status: Int,
    val subtitle_e: String,
    val subtitle_s: Any,
    val title_e: String,
    val title_s: String,
    val title: String,
    val trailer_duration: String,
    val trailer_path: String,
    val type: Int,
    val updated_at: String,
//    val video_quality: String,
    val web_image_e: String,
    val web_image_s: String,
    val web_poster_e: String,
    val web_poster_s: String,
    val writer: String
)
data class EpisodeData(
    val actor: String,
    val banner_status: Int,
    val cat_id: String,
    val content_duration: String,
    val content_mode: Int,
    val content_type: Int,
    val created_at: String,
    val description_e: String,
    val description_s: String,
    val director: String,
    val download: Int,
    val id: Int,
    val image_e: String,
    val image: String,
    val image_s: String,
    val is_draft: String,
    val keyword: String,
    val mambo_org: String,
    val path: String,
    val poster_e: String,
    val poster_s: String,
    val related_content_id: Any,
    val release_date: String,
    val release_year: Int,
    val runtime: Int,
    val schedule: String,
    val schedule_date_time: String,
    val slug: String,
    val status: Int,
    val subtitle_e: String,
    val subtitle_s: Any,
    val title_e: String,
    val title_s: String,
    val title: String,
    val trailer_duration: String,
    val trailer_path: String,
    val type: Int,
    val updated_at: String,
//    val video_quality: String,
    val web_image_e: String,
    val web_image_s: String,
    val web_poster_e: String,
    val web_poster_s: String,
    val writer: String
)